### PR TITLE
Move from alpine to slim python image

### PR DESCRIPTION
**Pull request by pyropy**
Moved from alpineto slim python image #33

### CODE REVIEW

**Comment by pyropy** [comment]
@cmccandless As in previous PR I can't assign you :disappointed:

**Comment by cmccandless** [comment]
Looks like the CI tests are failing. This may not be due to your changes, as there are other failing runs in the history. I will try to fix the tests, and then we can update this PR to verify that everything is as it should be before merging.

**Comment by pyropy** [comment]
> Looks like the CI tests are failing. This may not be due to your changes, as there are other failing runs in the history. I will try to fix the tests, and then we can update this PR to verify that everything is as it should be before merging.

We can make a issue and I can help you out with the tests :smile:

**Comment by cmccandless** [comment]
See #39

**Comment by cmccandless** [comment]
Looks good! Thanks @pyropy for starting this effort. Sorry it took so long to resolve the failures external to this PR.

**Pull request merged**
