### PR TITLE
Change to AGPL

### PR DESCRIPTION
**Pull request by iHiD**
We are changing all tooling to use AGPL instead of MIT to protect ourselves against proprietisation. Please see https://github.com/exercism/exercism/issues/5334 for context.

@alirezaghey @cmccandless @yawpitch @ErikSchierboom - please can you confirm you are happy as the contributors. Thank you :)

### CODE REVIEW

**Comment by cmccandless** [comment]
I'm fine with this, but the existing [LICENCE](https://github.com/exercism/python-test-runner/blob/master/LICENCE) file needs to be removed with these changes.

**Comment by yawpitch** [comment]
Fine with me.

**Comment by alirezaghey** [comment]
Hi Jeremy,
Sounds good to me. Thank you for asking!

**Comment by alirezaghey** [comment]
Hi Jeremy,
Sounds good to me. Thank you for asking!

**Comment by iHiD** [comment]
Thank you everyone.

@ErikSchierboom Once you ok this, please remove the old licence file and merge. Thanks! :)

**Comment by ErikSchierboom** [comment]
Done

**Pull request merged**
