### PR TITLE
[Test Runner Report] Added lasgana_test.py Check

### PR DESCRIPTION
**Pull request by BethanyG**
Added check for `lasagna_test.py` in the `err.chain`, so that the tracback could be trimmed to only the friendly ImportError message.  Left other exercises with full traceback.

### CODE REVIEW

**Review by kotp — COMMENTED** [review]
There is text after the last line.  Also known as "The last line is missing an EOL."

**Comment by BethanyG** [comment]
(facepalm).  Ok. Lets try this one more time....

**Comment by BethanyG** [comment]
And the CI remains unimpressed.  Gonna have to call in a consult.  Same docker container should be same result.  I just don't even have a clue as to why its not.

**Review by kotp — APPROVED** [review]

**Comment by kotp** [comment]
Approved in case we can get a passing under the cover of Docker…

**Pull request merged**
